version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.27.0
    - 8.29.0
    - 8.30.0
    - 8.30.1
    - 8.31.0
    - 8.33.1
    - 8.34.0
    - 8.35.1
    - 8.36.1
    - 8.36.2
    - 8.38.0
    - 8.39.0
  - dependency-name: nunomaduro/collision
    versions:
    - 5.4.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.4
  - dependency-name: laravel/tinker
    versions:
    - 2.6.1
  - dependency-name: facade/ignition
    versions:
    - 2.5.10
    - 2.5.12
